### ISSUE TITLE
Conversion functions required

### ISSUE THREAD

**Issue by manosk** [dias-epfl/raw#1]
Need to convert ("raw") data between data types.

Motivation:
For instance, a CSV generator only dumps out strings. 
Schemas should be applied "later" by applying conversion functions 

This facilitates creating views of raw data too

Example:

csvWithSchema := for (r <- csv; a := int(r.col1), b := float(r.col2), a > 10) yield list b

csvWithSchema can then be used by future queries

**Comment by miguel-branco** [comment]
Done as part of latest Simplifier
